### ISSUE TITLE
Missing test Project

### ISSUE THREAD

**Issue by ssossou** [praveenkrjha/DotNetCoreApiMsTest#1]
Hi Praveenkrjha,

I believe the test project i missing from the repository, either not checked in or the not shared public.

**Comment by praveenkrjha** [comment]
Thanks ssossou for pointing this out. I don't know how that got missed. Added test project.
Also, integrated OpenCover to check code coverage of your .NET core API.
Run "DotNetCoreApiMsTest\SampleDotNetCoreApiTest\TestRunner2.cmd" from command prompt to check code coverage of your test cases.
